---
title: "Toujas-Tort"
format: html
editor: visual
repo-url: https://github.com/Lou-Ann83/test-grades.git
---

## Intro

```{r}
here::i_am("test-grades.Rproj")
library(ggplot2)
library(dplyr)
library(here)
library(vroom)
library(stringr)
library(tidyr)
library(readr)
```
## Question 1

```{r}
courses <- read.csv("data/courses.csv") 
```

## Question 2

```{r}
courses <- courses |> rename(`course name`= course, identifier = course_id, `Number of exams`= nb_grades ) |> arrange((`course name`))

knitr::kable(courses)
```
## Question 3 

```{r}
students <- read_delim(here("data", "students.csv"), col_types = cols(group = col_factor(), birth_date= col_date(), sex = col_factor(), id = col_integer()))
str(students)
print("The birth_date column of the students data frame is a Date column ")
```
## Question 4

```{r}
grades <- read_delim(here("data", "grades.csv"), delim = ":", na = "$")
str(grades)
```
## Question 5

```{r}
nb_student_per_grp <- students |> distinct(id, group) |> count(group)
ggplot(nb_student_per_grp, aes(x=n, y=group))+
  geom_col()
```

## Question 6

```{r}
Gender_balance <- students |> count(group,sex)
ggplot(Gender_balance, aes(x = group,y=n, fill = sex))+
      geom_col(position = "fill")
```
## Question 7

```{r}
library(lubridate)
event_date <- date(students$birth_date)
students <- students |> mutate(age=time_length(today()-event_date, unit="year"), age = as.integer(students$age)) 

students_age <- students|> distinct(id, age) |> count(age)
ggplot(students_age, aes(age, n))+
  geom_col()
```

## Question 8

```{r}
age_per_group <- students |> count(group, age) 
median_age_grp <- age_per_group |> group_by(group)|> summarise(median = median(age), median = as.integer(median_age_grp$median))
knitr::kable(median_age_grp)
```

## Question 9

```{r}
oldest <- students |> distinct(group, age) |> group_by(group) |> slice_max(age) |> arrange(desc(age))
```

## Question  10

```{r}
nb_grades = sum(!is.na(grades$grade))
glue::glue("There is {nb_grades} grades ")
```
## Question 11

```{r}
GWM_grades <- grades |> left_join(students, by = "id") |> filter(course_id==10) |> group_by(group) |> summarise(mean_grp = mean(grade, na.rm=TRUE))

ggplot(GWM_grades, aes(x=group, y=mean_grp))+
  geom_col()
```


